[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-Wl,-rpath,/Users/zaidhumayun/.pyenv/versions/3.12.0/lib",
  "-C", "link-arg=-L/Users/zaidhumayun/.pyenv/versions/3.12.0/lib",
  "-C", "link-arg=-lpython3.12"
]
